#!/usr/bin/env python
# refer to nvme-cli register dump instructions at https://netorg243736.sharepoint.com/Engineer%20Wiki/NVME%20SFX%20passthru%20registers%20read.aspx
#

import re
import os
import time
import datetime
import binascii

if __name__ == '__main__':
    print "#"
    print "#  Auto generated by parser_nvmedump.py on ", datetime.date.today().ctime()
    print "# "
    print

    os.system("nvme admin-passthru -o 0xd0 -i ../software/drivers/include/nvme_cli_regsv.list /dev/sfdv0n1 -w -l 0x80000")
    os.system("nvme admin-passthru -o 0xd1 /dev/sfdv0n1 -r -l 0x20000 -b > binary_file")

    time.sleep(0.2)
    f1 = open('../software/drivers/include/parser_regs.list', 'rU')
    f2 = open('./binary_file', 'rb')

    strout = ''

    for line in f1:
        hexdata = binascii.hexlify(f2.read(1))
        hexdata = binascii.hexlify(f2.read(1)) + hexdata
        hexdata = binascii.hexlify(f2.read(1)) + hexdata
        hexdata = binascii.hexlify(f2.read(1)) + hexdata
        strout += line.strip() + ' 0x' + hexdata + '\n'

    fo = open('./nvme_regsout.csv', 'w')
    fo.write(strout)
    fo.close()

    os.system("rm ./binary_file")

